services:
  app:
    build: 
      context: .
      dockerfile: docker/Dockerfile # upewnij się, że ścieżka pasuje
    volumes:
      - ./src:/app/src           # Mapowanie kodu (Hot Reloading)
      - ./data:/app/data         # Persystencja danych finansowych
      - ./logs:/app/logs         # Logi dostępne na hostingu
      - ./config:/app/config     # Konfiguracja instrumentów
    env_file:
      - .env                     
    stdin_open: true 
    tty: true

  minio:
    image: minio/minio
    container_name: minio_storage
    ports:
      - "9000:9000" #API s3
      - "9001:9001" #Console
    environment:
      - MINIO_ROOT_USER = ${MINIO_USER}
      - MINIO_ROOT_PASSWORD = ${MINIO_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-adress ":9001"

    createbuckets:
      image: minio/mc
      depends_on:
        - minio
    
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set local_minio http://minio:9000 admin password) do echo 'Waiting for MinIO...' && sleep 1; done;
      /usr/bin/mc mb --ignore-existing local_minio/bronze;
      exit 0;
      "

volumes:
  minio_data:
